<?php

namespace App\Facades;

use illuminate\Support\Facades\Facade;

class ApiExample extends Facade
{
    protected static function getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'api-example';
    }
}